apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-team
  namespace: frontend
subjects:
  - kind: Group
    name: frontend-team # Matches "O" field in certificate
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole # Changed from "Role" to "ClusterRole"
  name: developer
  apiGroup: rbac.authorization.k8s.io
