apiVersion: v1
kind: Namespace
metadata:
  name: sticky-session-secure
  labels:
    kubernetes.io/metadata.name: sticky-session-secure
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
