apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: mongo-lab
data:
  mongod.conf: |
    # mongod.conf
    # for documentation of all options, see:
    #   http://docs.mongodb.org/manual/reference/configuration-options/

    # Where and how to store data.
    storage:
      dbPath: /data/db

    replication:
      replSetName: "rs0"

    net:
      port: 27017
      bindIp: 0.0.0.0
      bindIpAll: true
